from __future__ import annotations

from copy import deepcopy
from typing import Any

from . import SCHEMA

TEMPLATES: dict[str, dict[str, Any]] = {
    "character-platformer": {
        "schema": SCHEMA,
        "name": "hero",
        "kind": "character",
        "view": "side",
        "description": "",
        "canvas": {"width": 32, "height": 32},
        "colorMode": "indexed",
        "palette": "endesga-32",
        "grid": {"width": 16, "height": 16},
        "pivot": {"x": 16, "y": 32},
        "sources": {
            "dir": "raw",
            "cleanDir": "clean",
            "pattern": "{tag}_{frame:02d}.png",
            "cornerKey": True,
            "keyColors": ["#FF00FF", "#00FF00"],
            "tolerance": 28,
            "anchor": "bottom-center",
            "padding": 1,
            "scaleMode": "contain",
        },
        "layers": [{"name": "sprite"}],
        "tags": [
            {"name": "idle", "frames": 4, "duration": 140},
            {"name": "walk", "frames": 6, "duration": 80},
            {"name": "jump", "frames": 3, "duration": 100},
        ],
    },
    "character-topdown": {
        "schema": SCHEMA,
        "name": "actor",
        "kind": "character",
        "view": "top-down",
        "description": "",
        "canvas": {"width": 16, "height": 16},
        "colorMode": "indexed",
        "palette": "endesga-32",
        "grid": {"width": 16, "height": 16},
        "pivot": {"x": 8, "y": 12},
        "sources": {
            "dir": "raw",
            "cleanDir": "clean",
            "pattern": "{tag}_{frame:02d}.png",
            "cornerKey": True,
            "keyColors": ["#FF00FF", "#00FF00"],
            "tolerance": 28,
            "anchor": "bottom-center",
            "padding": 1,
        },
        "layers": [{"name": "sprite"}],
        "tags": [
            {"name": "idle-down", "frames": 2, "duration": 200},
            {"name": "walk-down", "frames": 4, "duration": 100},
            {"name": "walk-left", "frames": 4, "duration": 100},
            {"name": "walk-right", "frames": 4, "duration": 100},
            {"name": "walk-up", "frames": 4, "duration": 100},
        ],
    },
    "character-turnaround": {
        "schema": SCHEMA,
        "name": "hero-turnaround",
        "kind": "concept",
        "view": "turnaround",
        "description": "",
        "canvas": {"width": 64, "height": 64},
        "colorMode": "indexed",
        "palette": "endesga-32",
        "grid": {"width": 16, "height": 16},
        "pivot": {"x": 32, "y": 64},
        "sources": {
            "dir": "raw",
            "cleanDir": "clean",
            "pattern": "{tag}_{frame:02d}.png",
            "cornerKey": True,
            "keyColors": ["#FF00FF", "#00FF00"],
            "tolerance": 28,
            "anchor": "bottom-center",
            "padding": 2,
        },
        "layers": [{"name": "sprite"}],
        "tags": [
            {"name": "front", "frames": 1, "duration": 200},
            {"name": "three-quarter", "frames": 1, "duration": 200},
            {"name": "side", "frames": 1, "duration": 200},
            {"name": "back", "frames": 1, "duration": 200},
        ],
    },
    "portrait": {
        "schema": SCHEMA,
        "name": "portrait",
        "kind": "portrait",
        "view": "front",
        "description": "",
        "canvas": {"width": 80, "height": 80},
        "colorMode": "indexed",
        "palette": "endesga-32",
        "sources": {
            "dir": "raw",
            "cleanDir": "clean",
            "pattern": "{tag}_{frame:02d}.png",
            "cornerKey": True,
            "keyColors": ["#FF00FF", "#00FF00"],
            "tolerance": 32,
            "anchor": "center",
            "padding": 4,
        },
        "layers": [{"name": "paint"}],
        "tags": [{"name": "bust", "frames": 1, "duration": 200}],
    },
    "prop": {
        "schema": SCHEMA,
        "name": "prop",
        "kind": "prop",
        "view": "side",
        "description": "",
        "canvas": {"width": 32, "height": 32},
        "colorMode": "indexed",
        "palette": "endesga-32",
        "pivot": {"x": 16, "y": 32},
        "sources": {
            "dir": "raw",
            "cleanDir": "clean",
            "pattern": "{tag}_{frame:02d}.png",
            "cornerKey": True,
            "keyColors": ["#FF00FF", "#00FF00"],
            "tolerance": 28,
            "anchor": "bottom-center",
            "padding": 1,
        },
        "layers": [{"name": "sprite"}],
        "tags": [{"name": "idle", "frames": 2, "duration": 180}],
    },
    "tileset-16": {
        "schema": SCHEMA,
        "name": "tileset",
        "kind": "tileset",
        "view": "top-down",
        "description": "",
        "canvas": {"width": 16, "height": 16},
        "colorMode": "indexed",
        "palette": "endesga-32",
        "grid": {"width": 16, "height": 16},
        "sources": {
            "dir": "raw",
            "cleanDir": "clean",
            "pattern": "{tag}_{frame:02d}.png",
            "cornerKey": False,
            "keyColors": [],
            "tolerance": 8,
            "anchor": "center",
            "padding": 0,
            "scaleMode": "none",
        },
        "layers": [{"name": "tile"}],
        "tags": [
            {"name": "grass", "frames": 1, "duration": 100},
            {"name": "dirt", "frames": 1, "duration": 100},
            {"name": "stone", "frames": 1, "duration": 100},
            {"name": "water", "frames": 2, "duration": 200},
        ],
    },
    "ui-button": {
        "schema": SCHEMA,
        "name": "button",
        "kind": "ui",
        "view": "front",
        "description": "",
        "canvas": {"width": 48, "height": 16},
        "colorMode": "indexed",
        "palette": "endesga-32",
        "sources": {
            "dir": "raw",
            "cleanDir": "clean",
            "pattern": "{tag}_{frame:02d}.png",
            "cornerKey": True,
            "keyColors": ["#FF00FF", "#00FF00"],
            "tolerance": 28,
            "anchor": "center",
            "padding": 0,
        },
        "layers": [{"name": "button"}],
        "slices": [{"name": "nine", "x": 0, "y": 0, "w": 48, "h": 16, "ninePatch": [4, 4, 40, 8]}],
        "tags": [
            {"name": "normal", "frames": 1, "duration": 100},
            {"name": "hover", "frames": 1, "duration": 100},
            {"name": "pressed", "frames": 1, "duration": 100},
        ],
    },
    "fx": {
        "schema": SCHEMA,
        "name": "fx",
        "kind": "fx",
        "view": "front",
        "description": "",
        "canvas": {"width": 32, "height": 32},
        "colorMode": "indexed",
        "palette": "endesga-32",
        "pivot": {"x": 16, "y": 16},
        "sources": {
            "dir": "raw",
            "cleanDir": "clean",
            "pattern": "{tag}_{frame:02d}.png",
            "cornerKey": True,
            "keyColors": ["#FF00FF", "#00FF00"],
            "tolerance": 28,
            "anchor": "center",
            "padding": 1,
        },
        "layers": [{"name": "fx"}],
        "tags": [{"name": "burst", "frames": 6, "duration": 70}],
    },
}


def list_templates() -> list[dict[str, Any]]:
    items = []
    for name, spec in TEMPLATES.items():
        items.append(
            {
                "id": name,
                "kind": spec.get("kind"),
                "canvas": spec.get("canvas"),
                "tags": [t["name"] for t in spec.get("tags") or []],
                "colorMode": spec.get("colorMode"),
                "palette": spec.get("palette"),
            }
        )
    return items


def get_template(name: str) -> dict[str, Any]:
    if name not in TEMPLATES:
        known = ", ".join(sorted(TEMPLATES))
        raise KeyError(f"Unknown template {name!r}. Available: {known}")
    return deepcopy(TEMPLATES[name])
